name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

      - name: Login to Docker Hub
        if: steps.changes.outputs.client == 'true' || steps.changes.outputs.server == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: 'Build:dockerimage-client'
        if: steps.changes.outputs.client == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-client:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-client:${{github.sha}}

      - name: 'Build:dockerimage-server'
        if: steps.changes.outputs.server == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-server:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-server:${{github.sha}}

      - name: 'Update client service'
        if: steps.changes.outputs.client == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.CLIENT_WEBHOOK }}
          preventFailureOnNoResponse: true

      - name: 'Update server service'
        if: steps.changes.outputs.server == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.SERVER_WEBHOOK }}
          preventFailureOnNoResponse: true
