name: Run tests on pull request

on:
  pull_request:
    branches:
    - main

jobs:
  prepare:
    name: Prepare changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.changes.outputs.client }}
      server: ${{ steps.changes.outputs.server }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Filter changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          client:
            - 'client/**'
          server:
            - 'server/**'


  server-tests:
    name: Run server tests
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.server == 'true' }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: server/yarn.lock
      - run: yarn
      - run: yarn test
      - run: yarn test:e2e
      

  client-tests:
    name: Run client tests
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.client == 'true' }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - run: yarn
      - run: yarn test

