name: Run tests on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: buzz-code/multi-repo-codespace/.github/workflows/reusable-tests.yml@main
    with:
      run_e2e: true

